const SUPABASE_URL = 'https://tzdjugjaomfyircjvhxp.supabase.co';
const SUPABASE_ANON_KEY = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InR6ZGp1Z2phb21meWlyY2p2aHhwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODEyNTkzMjIsImV4cCI6MjA5NjgzNTMyMn0.DyoEAilo99tdZVVgbNFZ0xMgVRUq8EVFa1Bj4MTu-tM';
const sb = supabase.createClient(SUPABASE_URL, SUPABASE_ANON_KEY);
let state = { player:null, players:[], matches:[], predictions:[], groups:[], groupPreds:[], bonusPreds:[], bonusResults:null };
const $ = id => document.getElementById(id);
const flagMap = {Portugal:'🇵🇹',Brazil:'🇧🇷',Brasil:'🇧🇷',Argentina:'🇦🇷',Spain:'🇪🇸',Espanha:'🇪🇸',France:'🇫🇷',França:'🇫🇷',Germany:'🇩🇪',Alemanha:'🇩🇪',Italy:'🇮🇹',Itália:'🇮🇹',England:'🏴',Inglaterra:'🏴',Mexico:'🇲🇽',México:'🇲🇽','South Africa':'🇿🇦','África do Sul':'🇿🇦','South Korea':'🇰🇷','Coreia do Sul':'🇰🇷','Czech Republic':'🇨🇿','República Checa':'🇨🇿',Canada:'🇨🇦',Canadá:'🇨🇦','Bosnia & Herzegovina':'🇧🇦','Bósnia e Herzegovina':'🇧🇦',USA:'🇺🇸','United States':'🇺🇸','Estados Unidos':'🇺🇸',Uruguay:'🇺🇾',Uruguai:'🇺🇾',Colombia:'🇨🇴',Colômbia:'🇨🇴',Japan:'🇯🇵',Japão:'🇯🇵',Morocco:'🇲🇦',Marrocos:'🇲🇦',Croatia:'🇭🇷',Croácia:'🇭🇷',Belgium:'🇧🇪',Bélgica:'🇧🇪',Netherlands:'🇳🇱','Países Baixos':'🇳🇱',Switzerland:'🇨🇭',Suíça:'🇨🇭',Denmark:'🇩🇰',Dinamarca:'🇩🇰',Sweden:'🇸🇪',Suécia:'🇸🇪',Norway:'🇳🇴',Noruega:'🇳🇴',Poland:'🇵🇱',Polónia:'🇵🇱',Serbia:'🇷🇸',Sérvia:'🇷🇸',Senegal:'🇸🇳',Ghana:'🇬🇭',Nigeria:'🇳🇬',Nigéria:'🇳🇬',Egypt:'🇪🇬',Egito:'🇪🇬',Qatar:'🇶🇦',Australia:'🇦🇺',Austrália:'🇦🇺','Saudi Arabia':'🇸🇦','Arábia Saudita':'🇸🇦'};
const f = team => `${flagMap[team]||''} ${team}`;
function outcome(h,a){ if(h===null||a===null||h===undefined||a===undefined) return null; return h>a?'home':h<a?'away':'draw'; }
function matchPoints(pred, match){ if(match.home_score===null||match.away_score===null||pred.home_prediction===null||pred.away_prediction===null) return 0; if(pred.home_prediction===match.home_score && pred.away_prediction===match.away_score) return 5; return outcome(pred.home_prediction,pred.away_prediction)===outcome(match.home_score,match.away_score)?3:0; }
function groupPoints(gp, group){ if(!group.final_order || !gp.predicted_order) return 0; return gp.predicted_order.reduce((sum,t,i)=>sum+(group.final_order[i]===t?3:0),0); }
function bonusPoints(bp){ const r=state.bonusResults||{}; let pts=0; if(bp?.champion && r.champion && bp.champion.trim().toLowerCase()===r.champion.trim().toLowerCase()) pts+=10; if(bp?.runner_up && r.runner_up && bp.runner_up.trim().toLowerCase()===r.runner_up.trim().toLowerCase()) pts+=5; if(bp?.top_scorer && r.top_scorer && bp.top_scorer.trim().toLowerCase()===r.top_scorer.trim().toLowerCase()) pts+=5; return pts; }
async function loadAll(){
  const [players,matches,preds,groups,gpreds,bpreds,bres] = await Promise.all([
    sb.from('players').select('*').order('id'), sb.from('matches').select('*').order('kickoff',{ascending:true}), sb.from('predictions').select('*'), sb.from('groups').select('*').order('name'), sb.from('group_predictions').select('*'), sb.from('bonus_predictions').select('*'), sb.from('bonus_results').select('*').eq('id',1).single()
  ]);
  state.players=players.data||[]; state.matches=matches.data||[]; state.predictions=preds.data||[]; state.groups=groups.data||[]; state.groupPreds=gpreds.data||[]; state.bonusPreds=bpreds.data||[]; state.bonusResults=bres.data||{};
  renderPlayers(); if(state.player){ state.player = state.players.find(p=>p.id===state.player.id)||state.player; renderApp(); }
}
function renderPlayers(){ $('playerSelect').innerHTML = state.players.map(p=>`<option value="${p.id}">${p.name}</option>`).join(''); }
async function login(){ const p=state.players.find(x=>String(x.id)===$('playerSelect').value); if(!p || p.pin !== $('pinInput').value){ alert('Nome ou PIN errado.'); return; } state.player=p; localStorage.setItem('playerId',p.id); $('login').classList.add('hidden'); $('app').classList.remove('hidden'); renderApp(); }
function renderApp(){ $('who').textContent = state.player.name; $('adminBadge').classList.toggle('hidden',!state.player.is_admin); $('adminBonus').classList.toggle('hidden',!state.player.is_admin); $('adminGroups').classList.toggle('hidden',!state.player.is_admin); renderRanking(); renderBonus(); renderGroups(); renderMatches(); }
function renderRanking(){ const rows=state.players.map(p=>{ let pts=0; state.predictions.filter(x=>x.player_id===p.id).forEach(pr=>{ const m=state.matches.find(mm=>mm.id===pr.match_id); if(m) pts+=matchPoints(pr,m); }); state.groupPreds.filter(x=>x.player_id===p.id).forEach(gp=>{ const g=state.groups.find(gg=>gg.id===gp.group_id); if(g) pts+=groupPoints(gp,g); }); pts += bonusPoints(state.bonusPreds.find(x=>x.player_id===p.id)); return {name:p.name, pts}; }).sort((a,b)=>b.pts-a.pts); $('ranking').innerHTML=`<table class="table"><tr><th>#</th><th>Nome</th><th>Pontos</th></tr>${rows.map((r,i)=>`<tr><td>${i+1}</td><td>${r.name}</td><td><b>${r.pts}</b></td></tr>`).join('')}</table>`; }
function renderBonus(){ const bp=state.bonusPreds.find(x=>x.player_id===state.player.id)||{}; $('championInput').value=bp.champion||''; $('runnerInput').value=bp.runner_up||''; $('scorerInput').value=bp.top_scorer||''; if(state.player.is_admin){ $('realChampion').value=state.bonusResults.champion||''; $('realRunner').value=state.bonusResults.runner_up||''; $('realScorer').value=state.bonusResults.top_scorer||''; } }
async function saveBonus(){ await sb.from('bonus_predictions').upsert({player_id:state.player.id, champion:$('championInput').value, runner_up:$('runnerInput').value, top_scorer:$('scorerInput').value, updated_at:new Date().toISOString()},{onConflict:'player_id'}); await loadAll(); alert('Bónus guardado.'); }
async function saveBonusResults(){ await sb.from('bonus_results').upsert({id:1, champion:$('realChampion').value, runner_up:$('realRunner').value, top_scorer:$('realScorer').value, updated_at:new Date().toISOString()}); await loadAll(); alert('Resultados bónus guardados.'); }
function orderSelect(id, teams, selected){ return `<select id="${id}">${teams.map(t=>`<option ${t===selected?'selected':''}>${t}</option>`).join('')}</select>`; }
function renderGroups(){ if(!state.groups.length){ $('groups').innerHTML='<p class="hint">Ainda não há grupos criados.</p>'; $('groupResults').innerHTML=''; return; } $('groups').innerHTML=state.groups.map(g=>{ const gp=state.groupPreds.find(x=>x.player_id===state.player.id && x.group_id===g.id); const arr=gp?.predicted_order||g.teams; return `<div class="groupbox"><h3>${g.name}</h3><div class="order">${[0,1,2,3].map(i=>`<label>${i+1}.º ${orderSelect(`gp-${g.id}-${i}`,g.teams,arr[i])}</label>`).join('')}</div><button onclick="saveGroupPrediction(${g.id})">Guardar ${g.name}</button></div>`; }).join(''); if(state.player.is_admin){ $('groupResults').innerHTML=state.groups.map(g=>{ const arr=g.final_order||g.teams; return `<div class="groupbox"><h3>${g.name}</h3><div class="order">${[0,1,2,3].map(i=>`<label>${i+1}.º ${orderSelect(`gr-${g.id}-${i}`,g.teams,arr[i])}</label>`).join('')}</div><button onclick="saveGroupResult(${g.id})">Guardar classificação final</button></div>`; }).join(''); } }
async function saveGroupPrediction(groupId){ const order=[0,1,2,3].map(i=>$(`gp-${groupId}-${i}`).value); if(new Set(order).size!==4){ alert('Não podes repetir equipas no mesmo grupo.'); return; } await sb.from('group_predictions').upsert({player_id:state.player.id, group_id:groupId, predicted_order:order, updated_at:new Date().toISOString()},{onConflict:'player_id,group_id'}); await loadAll(); alert('Aposta do grupo guardada.'); }
async function saveGroupResult(groupId){ const order=[0,1,2,3].map(i=>$(`gr-${groupId}-${i}`).value); if(new Set(order).size!==4){ alert('Não podes repetir equipas.'); return; } await sb.from('groups').update({final_order:order}).eq('id',groupId); await loadAll(); alert('Classificação final guardada.'); }
function renderMatches(){ if(!state.matches.length){ $('matches').innerHTML='<p class="hint">Ainda não há jogos.</p>'; return; } $('matches').innerHTML=state.matches.map(m=>{ const pr=state.predictions.find(x=>x.player_id===state.player.id && x.match_id===m.id)||{}; const admin = state.player.is_admin ? `<div class="scoreline"><label>Golos ${m.home_team}<input id="rh-${m.id}" type="number" value="${m.home_score??''}"></label><label>Golos ${m.away_team}<input id="ra-${m.id}" type="number" value="${m.away_score??''}"></label><button onclick="saveResult(${m.id})">Guardar resultado</button></div>` : ''; return `<div class="match"><div class="teams">${f(m.home_team)} vs ${f(m.away_team)}</div><div class="small">${m.kickoff?new Date(m.kickoff).toLocaleString('pt-PT'):''}</div><div class="scoreline"><label>${m.home_team}<input id="ph-${m.id}" type="number" value="${pr.home_prediction??''}"></label><label>${m.away_team}<input id="pa-${m.id}" type="number" value="${pr.away_prediction??''}"></label><button onclick="savePrediction(${m.id})">Guardar aposta</button><span class="small">${pr.id?'Pontos: '+matchPoints(pr,m):''}</span></div>${admin}</div>`; }).join(''); }
async function savePrediction(matchId){ const h=$(`ph-${matchId}`).value, a=$(`pa-${matchId}`).value; if(h===''||a===''){ alert('Preenche os dois resultados.'); return; } await sb.from('predictions').upsert({player_id:state.player.id, match_id:matchId, home_prediction:Number(h), away_prediction:Number(a)},{onConflict:'player_id,match_id'}); await loadAll(); alert('Aposta guardada.'); }
async function saveResult(matchId){ await sb.from('matches').update({home_score:Number($(`rh-${matchId}`).value), away_score:Number($(`ra-${matchId}`).value)}).eq('id',matchId); await loadAll(); alert('Resultado guardado.'); }
$('loginBtn').onclick=login; $('logoutBtn').onclick=()=>{localStorage.removeItem('playerId'); location.reload();}; $('saveBonusBtn').onclick=saveBonus; $('saveBonusResultsBtn').onclick=saveBonusResults;
loadAll().then(()=>{ const id=localStorage.getItem('playerId'); if(id){ const p=state.players.find(x=>String(x.id)===id); if(p){ state.player=p; $('login').classList.add('hidden'); $('app').classList.remove('hidden'); renderApp(); } } });
